[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"